Repository Jim-Hodapp-Coaching/ambi, pull requests merged in 2022-04, with the labels that each got.

#16 Update create-git-hooks to create Git hooks dir if missing
  scripts/create-git-hooks
Labels: build system

#17 Update all Elixir dependencies to latest versions
  mix.lock
Labels: dependency update, backend

#18 Add a simple Ambi logo instead of the Bulma one.
  assets/static/images/ambi_logo.png
  lib/ambi_web/templates/layout/root.html.leex
Labels: enhancement, frontend
